"""
Setup script to add web scraping sources to the database
"""

import sqlite3
import os
import json

DB_PATH = os.path.join(os.path.dirname(__file__), "data", "scrapmaster.db")

# Create table if not exists
def create_sources_table():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS web_scraping_sources (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            url TEXT NOT NULL,
            type TEXT,
            category_id INTEGER,
            selectors TEXT,
            advance_config TEXT,
            presets TEXT,
            fetch_interval INTEGER,
            is_active INTEGER DEFAULT 1,
            last_fetched_at TEXT,
            created_at TEXT,
            content_type TEXT,
            scrape_depth INTEGER,
            use_browser INTEGER,
            max_pages INTEGER,
            delay INTEGER,
            pagination_type TEXT,
            pagination_selector TEXT,
            pagination_pattern TEXT,
            proxy_enabled INTEGER,
            proxy_provider TEXT,
            proxy_config TEXT,
            ssl_verify INTEGER,
            timeout INTEGER,
            connect_timeout INTEGER
        )
    """)
    conn.commit()
    conn.close()

def insert_sources():
    """Insert web scraping sources"""
    sources = [
        {
            "id": "1",
            "name": "Prothom Alo Latest",
            "url": "https://www.prothomalo.com/collection/latest",
            "type": "html",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:07",
            "created_at": "2026-03-07 18:59:24",
            "content_type": "articles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "7",
            "name": "Ittefaq",
            "url": "https://www.ittefaq.com.bd/",
            "type": "html",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:11",
            "created_at": "2026-03-07 18:59:24",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "17",
            "name": "BBC Travel",
            "url": "https://www.bbc.com/travel",
            "type": "scrape",
            "category_id": 4,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:11",
            "created_at": "2026-03-07 18:59:24",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "18",
            "name": "BBC Food",
            "url": "https://www.bbc.com/food",
            "type": "scrape",
            "category_id": 4,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:11",
            "created_at": "2026-03-07 18:59:24",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "21",
            "name": "BBC Bangla",
            "url": "https://www.bbc.com/bengali",
            "type": "html",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:11",
            "created_at": "2026-03-07 20:43:27",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "link",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "22",
            "name": "The Daily Star (Bangla) - Today's News",
            "url": "https://bangla.thedailystar.net/todays-news",
            "type": "scrape",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:15",
            "created_at": "2026-03-07 20:43:27",
            "content_type": "articles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "link",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "24",
            "name": "Jugantor",
            "url": "https://www.jugantor.com/latest",
            "type": "scrape",
            "category_id": 6,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:19",
            "created_at": "2026-03-07 20:43:27",
            "content_type": "articles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "link",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "25",
            "name": "Ittefaq Latest",
            "url": "https://www.ittefaq.com.bd/latest-news",
            "type": "html",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:22",
            "created_at": "2026-03-07 20:43:27",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "link",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "26",
            "name": "Samakal Latest",
            "url": "https://samakal.com/latest/news",
            "type": "scrape",
            "category_id": 6,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:26",
            "created_at": "2026-03-07 20:43:27",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 5,
            "pagination_type": "link",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "28",
            "name": "GSMArena BD Devices",
            "url": "https://www.gsmarena.com.bd/",
            "type": "scrape",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:30",
            "created_at": "2026-03-21 14:34:02",
            "content_type": "mobiles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "29",
            "name": "GSMArena Latest Devices",
            "url": "https://www.gsmarena.com/",
            "type": "scrape",
            "category_id": 12,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:31",
            "created_at": "2026-03-21 14:34:49",
            "content_type": "mobiles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "30",
            "name": "GSMArena News",
            "url": "https://www.gsmarena.com/",
            "type": "scrape",
            "category_id": 1,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:31",
            "created_at": "2026-03-21 14:36:59",
            "content_type": "articles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "31",
            "name": "BD News 24",
            "url": "https://bangla.bdnews24.com/",
            "type": "scrape",
            "category_id": 6,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:36",
            "created_at": "2026-03-22 15:01:26",
            "content_type": "articles",
            "scrape_depth": 2,
            "use_browser": 1,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "32",
            "name": "Teletalk Government Jobs",
            "url": "https://alljobs.teletalk.com.bd",
            "type": "html",
            "category_id": None,
            "selectors": None,
            "advance_config": None,
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": "2026-03-28 08:00:41",
            "created_at": "2026-03-27 19:51:25",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 50,
            "delay": 2,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 0,
            "timeout": 60,
            "connect_timeout": 20
        },
        {
            "id": "35",
            "name": "GitHub Trending Repositories",
            "url": "https://github.com/trending",
            "type": "scrape",
            "category_id": 3,
            "selectors": json.dumps({"repo_name": "h2 a", "description": "p", "language": ".f6 .d-inline-block", "stars": ".f6 .d-inline-block + .d-inline-block"}),
            "advance_config": json.dumps({"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "timeout": 45, "follow_redirects": True, "extract_dynamic": True, "wait_for_js": 3000}),
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": None,
            "created_at": "2026-03-31 02:46:23",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 1,
            "max_pages": 3,
            "delay": 5,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "36",
            "name": "Reddit Programming",
            "url": "https://www.reddit.com/r/programming/",
            "type": "scrape",
            "category_id": 2,
            "selectors": json.dumps({"title": "h3", "content": "[data-click-id=\"text\"]", "score": ".score", "comments": ".comments"}),
            "advance_config": json.dumps({"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "timeout": 60, "follow_redirects": True, "extract_dynamic": True, "wait_for_js": 5000, "proxy_enabled": True}),
            "presets": None,
            "fetch_interval": 1800,
            "is_active": 1,
            "last_fetched_at": None,
            "created_at": "2026-03-31 02:46:23",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 1,
            "max_pages": 5,
            "delay": 10,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
        {
            "id": "37",
            "name": "Stack Overflow Questions",
            "url": "https://stackoverflow.com/questions",
            "type": "scrape",
            "category_id": 3,
            "selectors": json.dumps({"title": "h3 a", "tags": ".tags .post-tag", "votes": ".vote-count-post", "answers": ".status strong"}),
            "advance_config": json.dumps({"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "timeout": 30, "follow_redirects": True, "extract_dynamic": False}),
            "presets": None,
            "fetch_interval": 3600,
            "is_active": 1,
            "last_fetched_at": None,
            "created_at": "2026-03-31 02:46:23",
            "content_type": "articles",
            "scrape_depth": 1,
            "use_browser": 0,
            "max_pages": 10,
            "delay": 5,
            "pagination_type": "none",
            "pagination_selector": None,
            "pagination_pattern": None,
            "proxy_enabled": 0,
            "proxy_provider": None,
            "proxy_config": None,
            "ssl_verify": 1,
            "timeout": 30,
            "connect_timeout": 10
        },
    ]
    
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    
    for source in sources:
        # Convert None to proper Python None for SQL
        selectors = source.get("selectors")
        advance_config = source.get("advance_config")
        presets = source.get("presets")
        last_fetched = source.get("last_fetched_at")
        cat_id = source.get("category_id")
        
        conn.execute("""
            INSERT OR REPLACE INTO web_scraping_sources (
                id, name, url, type, category_id, selectors, advance_config, presets, fetch_interval,
                is_active, last_fetched_at, created_at, content_type, scrape_depth, use_browser,
                max_pages, delay, pagination_type, pagination_selector, pagination_pattern,
                proxy_enabled, proxy_provider, proxy_config, ssl_verify, timeout, connect_timeout
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            source["id"], source["name"], source["url"], source["type"], cat_id,
            selectors, advance_config, presets, source["fetch_interval"],
            source["is_active"], last_fetched, source["created_at"], source["content_type"],
            source["scrape_depth"], source["use_browser"], source["max_pages"], source["delay"],
            source["pagination_type"], source["pagination_selector"], source["pagination_pattern"],
            source["proxy_enabled"], source["proxy_provider"], source["proxy_config"], source["ssl_verify"],
            source["timeout"], source["connect_timeout"]
        ))
    
    conn.commit()
    
    # Verify
    cursor = conn.execute("SELECT COUNT(*) as count FROM web_scraping_sources")
    count = cursor.fetchone()[0]
    
    conn.close()
    print(f"Added {len(sources)} web scraping sources to database (total: {count})")

if __name__ == "__main__":
    create_sources_table()
    insert_sources()
    print("Done!")